default_language_version:
  python: python3
  node: "16.17.0"
repos:
  - repo: https://github.com/sbidoul/whool
    rev: v0.5
    hooks:
      - id: whool-init
  - repo: https://github.com/oca/maintainer-tools
    rev: 1b216173c7d11cf682492aefc149f02627068174
    hooks:
      - id: oca-gen-external-dependencies
